### ISSUE TITLE
No Data making it to telegraf

### ISSUE THREAD

**Issue by timolow** [BSmithIO/OPNsense-Dashboard#1]
When running telegraf in debug mode I get the follow errors:

Error in plugin: error running pfctl: exit status 1: pfctl: /dev/pf: Permission denied

This was fixed by adding telegraf to sudoers file and adding:
use_sudo = true

after

[[inputs.pf]]

See https://www.reddit.com/r/homelab/comments/9woq6x/opnsense_telegraf_inputpf/ for details.

**Comment by zeit0dn1** [comment]
I was pulling my hair out on that one as well as it blocked the whole dashboard from loading for me.  Even with this work-around my gateway RTT and LOSS data wasn't loading.

Found out that I needed to make the below change in the telegraf.conf now that telegraf was in the sudoers file.
"sudo /usr/local/bin/telegraf_pfifgw.php"

Now everything in the dashboard works for me.

**Comment by timolow** [comment]
@zeit0dn1 that worked for me!

**Comment by BSmithIO** [comment]
I think I found an alternative solution to having to add telegraf to the sudoers. After you run `sudo pkg install telegraf` you can run

`printf 'telegraf_user="root" \ntelegraf_group="wheel" \ntelegraf_enable="YES"' > /etc/rc.conf.d/telegraf`

This will enable telegraf to start on boot as well as run as root.

**Comment by Oupsman** [comment]
If we plan to launch the plugins with sudo, don't we have to modify /usr/local/etc/telegraf.conf as well ?

[[inputs.exec]]
  commands = [
      "sudo /usr/local/bin/telegraf_pfifgw.php",
      "sudo /usr/local/bin/telegraf_temperature.sh"
  ]
  data_format = "influx"

**Comment by BSmithIO** [comment]
Whoops, you're right. I forgot to add that. I only added it to telegraf_pfifgw.php, as telegraf_temperature.sh seems to return temperatures without root.
