### ISSUE TITLE
For what is Elasticsearch required?

### ISSUE THREAD

**Issue by NKnusperer** [bsmithio/OPNsense-Dashboard#11]
Hello,
the [configure.md](https://github.com/bsmithio/OPNsense-Dashboard/blob/master/configure.md) instruct us to configure Elasticsearch but why is this required? As far as I understand only InfluxDB (for general metrics via Telegraf) and Graylog (as a Syslog receiver) is required.

**Comment by bsmithio** [comment]
Elasticsearch and MongoDB are for Graylog. Graylog parses the firewall log data from OPNsense and adds a country code for the world map to work.
