### ISSUE TITLE
Some simplifications

### ISSUE THREAD

**Issue by simplysoft** [bsmithio/OPNsense-Dashboard#13]
Thanks for great dashboard. 
We found that we could apply these simplification with no noticable issues:

1. It is possible to use standard telegraf OPNsense plugin and put the exec input config in `/usr/local/etc/telegraf.d/input_exec.conf` 
2. Run `telegraf_pfifgw.php` as telegraf user (from OPNsense plugin) seems working perfectly fine, no need to use `sudo` in command & add to sudoers

**Comment by bsmithio** [comment]
Thanks for letting me know about this! I just tried this and everything seems to be working. Definitely simplifies the configuration. I'll update the configuration guide.

**Comment by bsmithio** [comment]
Hi, I tried this out. Everything works except for Gateway info from telelgraf_pfifgw.php. Are you running Telegraf as root? 
![](https://i.imgur.com/hOlkOWY.png)

**Comment by NKnusperer** [comment]
For some reason Telegraf is also spamming the Syslog Widget like this:
![image](https://user-images.githubusercontent.com/179573/155077958-ad19c007-c542-4a98-a793-97e6e41239e4.png)

**Comment by bsmithio** [comment]
> For some reason Telegraf is also spamming the Syslog Widget like this:
> ![image](https://user-images.githubusercontent.com/179573/155077958-ad19c007-c542-4a98-a793-97e6e41239e4.png)
> 

You can add this line to sudoers

`Defaults:telegraf !log_allowed`

This will stop logging successful sudo attempts for the telegraf user.

**Comment by simplysoft** [comment]
No, we are running telegraf not as root. And `telegraf_pfifgw.php` also not with `sudo` so we don't have that spamming. It appears to be working fine, but we might be missing something. But we did not see any issues when running that script manually as the telegraf user. What metrics do you mean by gateway info?
We have not looked into the opnsense telegraf package, it might be that the package is making sure that telegraf user has access to opnsense files

**Comment by simplysoft** [comment]
You are right, without root it always reports all zero, we missed that. We did dig down a bit and the only thing where root permissions are really required are in https://github.com/opnsense/core/blob/master/src/etc/inc/util.inc#L74

If ignoring the `isvalidpid` check (commenting out the continue in https://github.com/opnsense/core/blob/50204d822b9fa1215caf8a01c777138d848af1a1/src/etc/inc/plugins.inc.d/dpinger.inc#L403), it works without root permissions.

Unfortunately seems no easy way to customize that without having to duplicate some of the dpinger logic into telegraf_pfifgw.php

**Comment by sticky99** [comment]
The step where you download the custom.conf to /usr/local/etc/telegraf.d didn't work for me as the telegraf.d directory didn't already exist. I eventually figured out that as I hadn't previously installed the telegraf plugin or enabled it, that that was the likely reason why it didn't exist.

Once I enabled the Telegraf plugin, the telegraf.d directory was created and that step could progress. So at the end where you describe enabling the plugin, I disabled it and re-enabled it once again.

**Comment by bsmithio** [comment]
> The step where you download the custom.conf to /usr/local/etc/telegraf.d didn't work for me as the telegraf.d directory didn't already exist. I eventually figured out that as I hadn't previously installed the telegraf plugin or enabled it, that that was the likely reason why it didn't exist.
> 
> Once I enabled the Telegraf plugin, the telegraf.d directory was created and that step could progress. So at the end where you describe enabling the plugin, I disabled it and re-enabled it once again.

Thanks, added commands to create the directory before downloading the config file to the guide.
