### ISSUE TITLE
Grafana InfluxDB data source variable not working

### ISSUE THREAD

**Issue by NKnusperer** [bsmithio/OPNsense-Dashboard#14]
I dot not get interface information when loading the Grafana Dashboard:
![image](https://user-images.githubusercontent.com/179573/154806189-45a6b75b-a5e2-4fa6-80d6-b66463930f10.png)
![image](https://user-images.githubusercontent.com/179573/154806685-23bff371-e696-4927-b871-f5dfb8139522.png)

When editing a panel and switching from `${datasSource}` to my actual data source it starts working:
![image](https://user-images.githubusercontent.com/179573/154806819-5ed2fb70-2ad5-4ff3-939b-87dafc483bdc.png)

**Comment by massaquah** [comment]
Just have a look at the issue I just created and closed. :)

**Comment by bsmithio** [comment]
Hi, could you try selecting your data sources on the top left?  

![](https://i.imgur.com/Yq82bek.png)

**Comment by NKnusperer** [comment]
Fixed by PR #16.
