### ISSUE TITLE
No data appears in Firewall groups

### ISSUE THREAD

**Issue by timolow** [BSmithIO/OPNsense-Dashboard#2]
I have followed your doc and find that messages are getting processed by graylog, but there are no outputs in grafana firewall panel or browsing the stream "OPNsense / filterlog" in graylog.  GeoIP database was installed with direction provided but had to remove the '\' in example between commands.

**Comment by BSmithIO** [comment]
This might be a time zone issue. To check, open the OPNsesne / filterlog stream, click on the clock, and then check "All Time".

**Comment by timolow** [comment]
You are correct, the data in graylog shows up if I adjust the timeframe, graylog seems to be operating in UTC time.  Grafana dashboard for Firewall and network stats for Gateway Loss and Gateway RTT are both lacking data.

**Comment by BSmithIO** [comment]
If you haven't already, you can change the timezone in the docker-compose file. Add `- TZ=yourtimezone` in the environment section for graylog, for good measure, you could set the timezone for each container. 

I've updated the docker-compose to include time zones and a link to valid time zones.

As for the Gateway values, you could try querying for those values on Grafana's Explore tab with this query 
```from(bucket: v.defaultBucket)
  |> range(start: -24h)
  |> filter(fn: (r) =>
    r._measurement == "gateways"
  )
```

Let me know if that returns anything.

**Comment by timolow** [comment]
I just updated the TZ info on graylog and it now returning data correctly in the graylog dashboard, still nothing in grafana for firewall panel.

The gateway returned a single gw, I have dual ISPs.

"Time","delay {gateway_name=""ISP_DHCP"", host=""cerberus.tld"", interface=""wan""}"
1637628551000,0
1637628561000,0
1637628571000,0
1637628581000,0
1637628591000,0
1637628601000,0
1637628611000,0
1637628621000,0

**Comment by timolow** [comment]
@BSmithIO The GW issue was solved here: https://github.com/BSmithIO/OPNsense-Dashboard/issues/1

**Comment by NKnusperer** [comment]
Same issue here, the Graylog stream is showing data but the firewall data in the Grafana dashboard is empty.
Also I do get some InfluxDB errors when loading the dashboard:
![image](https://user-images.githubusercontent.com/179573/154806189-45a6b75b-a5e2-4fa6-80d6-b66463930f10.png)

Not sure if this is related but all data are as expected except the firewall.
