### ISSUE TITLE
Grafana user/pw not detailed

### ISSUE THREAD

**Issue by sticky99** [bsmithio/OPNsense-Dashboard#21]
Maybe its because I've never used Grafana before, but I can't figure out how to login to Grafana from this guide

I've accessed the grafana container and viewed /etc/grafana/grafana.ini and I see the following

- # default admin user, created on startup
;admin_user = admin

- # default admin password, can be changed before first start of grafana,  or in profile settings
;admin_password = admin

but that combination doesn't work when I access the webpage on port 3000, and neither does the login creds for Influxdb or Graylog work on it either. 

So I'm obviously missing something obvious here.. but what?

**Comment by bsmithio** [comment]
Hi, the default username/password for grafana is opnsense/opnsense. Check out the docker-compose.yaml file for a few values that I recommend changing.

**Comment by sticky99** [comment]
Yeah, I edited the yaml file before the compose to change the graylog password etc. I just didn't see the user and password there that is now as obvious as the nose on my face. Bah...

Now having an issue adding the InfluxDB data source to Grafana, adding Elasticsearch worked without issue and I can see the elasticsearch data afterwards, but not knowing where the Grafana logs are stored on the container makes it more difficult to troubleshoot why the InfluxDB data source is having a problem. 

Essentially, I add in the config details as described and at the bottom, I click "Save & Test" and and error is shown saying "Error reading InfluxDB".  Do I need to use any option in the auth section? Initially it had "Basic Auth" selected so I went with that, but no matter what option I select (or selecting none), it doesn't make any difference, I still get the same error. 

The token I've used is the same token as used in the telegraf configuration on OpnSense, I'm presuming Organization is the same as on the Telegraf config too?

Within Influx, I can see that the connection from the firewall seems to be working (ie within Explore, I can click on the opnsense bucket, and select various different filters such as cpus etc). So Firewall to InfluxDB seems to be working, its just Grafana to InfluxDB that isn't working.

**Comment by bsmithio** [comment]
> Yeah, I edited the yaml file before the compose to change the graylog password etc. I just didn't see the user and password there that is now as obvious as the nose on my face. Bah...
> 
> Now having an issue adding the InfluxDB data source to Grafana, adding Elasticsearch worked without issue and I can see the elasticsearch data afterwards, but not knowing where the Grafana logs are stored on the container makes it more difficult to troubleshoot why the InfluxDB data source is having a problem.
> 
> Essentially, I add in the config details as described and at the bottom, I click "Save & Test" and and error is shown saying "Error reading InfluxDB". Do I need to use any option in the auth section? Initially it had "Basic Auth" selected so I went with that, but no matter what option I select (or selecting none), it doesn't make any difference, I still get the same error.
> 
> The token I've used is the same token as used in the telegraf configuration on OpnSense, I'm presuming Organization is the same as on the Telegraf config too?
> 
> Within Influx, I can see that the connection from the firewall seems to be working (ie within Explore, I can click on the opnsense bucket, and select various different filters such as cpus etc). So Firewall to InfluxDB seems to be working, its just Grafana to InfluxDB that isn't working.

You need to create an API token for Grafana. The Telegraf one will not work on Grafana, by default the Telegraf token doesn't have read access to the bucket.

**Comment by sticky99** [comment]
I generated that token when going through the InfluxDB configuration and even had it stored in my text file as for Grafana, but it never clicked that thats when it should be used. 

I'm not showing myself as being good at this am I?  At least they're simple fixes... 

I think I've it all configured now.. I'll play with a bit more before I make a fool of myself for a third time..

**Comment by bsmithio** [comment]
Hey, that's okay. This will help other people if they encounter these problems as well! If you have any other problems check the configuration guide, if it's not included on there then don't hesitate to ask for further help. Can I close this issue for now?
