### ISSUE TITLE
Suricata Dashboard Alert Information

### ISSUE THREAD

**Issue by sticky99** [bsmithio/OPNsense-Dashboard#22]
Since I've started using the Suricata dashboard I've noticed that the alerts within the Intrusion Detection part of the OpnSense GUI are no longer listed there. So presumably the action of sending them to Influx or Graylog  (I'm presuming Graylog?) results in them being deleted from the system, or at least from that part of the GUI.

This would be fine, except that the Alert Logs part of the Suricata dashboard doesn't tell me whether the traffic was allowed or blocked, or the SID in case I want to tweak the ruleset between alert or drop. This would be a lot of use when troubleshooting issues with specific websites, since without the action information I don't know if its something that was blocked, or noticed but allowed through, and without the SID information finding the specific rule to determine if it is set to alert or drop becomes more difficult (but still possible)

Is this something that I can easily add into the dashboard? Or is there a better approach?

**Comment by tonygauderman** [comment]
I never noticed that.. but had been sending the suricata alerts and drops to graylog before and via syslog and they are no longer going there either.  Not sure that using the log entries the way they are being used here will actually differentiate between drop and alert..  Right now I'm trying to tweak the InfluxDB query to return both the signature name and action, but I'm a little green when it comes to InfluxDB.

**Comment by tonygauderman** [comment]
I got mine to show on the dashboard with the following update.. it shows each item twice, once with the signature, once with action.. i'm sure there is a better way to do this, but this is what I have now..  

from(bucket: v.defaultBucket)
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "suricata")
  |> filter(fn: (r) => r["_field"] == "alert_signature" or r["_field"] == "alert_action")
  |> group()
  |> sort(columns: ["_time", "_field"], desc: true)
  |> limit(n:100)

**Comment by tonygauderman** [comment]
Removed that and just turned on the Event Type Transform and it shows on one row now..  and moved it up in the order..  
<img width="1288" alt="2022-03-01_16-38-00" src="https://user-images.githubusercontent.com/23512287/156260812-400f5afa-08de-4127-96fd-2178d324f637.png">

**Comment by sticky99** [comment]
That works.. Doesn't seem to be possible to add the SID via activating another field in the same way, but thats a lesser concern to me. Its possible to find the specific rule without the SID.

**Comment by tonygauderman** [comment]
I wonder if that could be done by modifying /usr/local/etc/telegraf.d/suricata.conf ??  I'm guessing there has to be a way to extract other fields from the alert in JSON.  the signature ID is there.. this is the piece of the json that contains it..  

"alert":{"action":"allowed","gid":1,"signature_id":2024897,"rev":2,"signature":"ET USER_AGENTS Go HTTP Client User-Agent","category":"Misc activity","severity":3,"metadata":{"attack_target":["Client_Endpoint"],"created_at":["2017_10_23"],"deployment":["Perimeter"],"former_category":["USER_AGENTS"],"signature_severity":["Major"],"updated_at":["2020_08_13"]}}

I can replace the signature name with any of the other fields in query, but I can't figure out how to add additional fields.

**Comment by sticky99** [comment]
So you mean add signature_id to the tag_keys within Suricata.conf?
