### ISSUE TITLE
More than 4 CPU's

### ISSUE THREAD

**Issue by zeit0dn1** [BSmithIO/OPNsense-Dashboard#3]
For those with other than 4 CPU's,  Edit the CPU panel in grafana and adjust the line to

    r.cpu =~ /cpu[0-7]$/ 

for 8 CPU systems as an example.

Perhaps there is a way to detect from the data, but I'm no expert.

**Comment by BSmithIO** [comment]
Good idea on retrieving the number of CPUs. I've updated the CPU usage panel to include a variable that retrieves the number of CPUs.

**Comment by zeit0dn1** [comment]
Works great.
