### ISSUE TITLE
Some metrics not written or correct

### ISSUE THREAD

**Issue by yenoromm** [bsmithio/OPNsense-Dashboard#32]
The n_users metric doesn't get written to InfluxDB and gateway loss is written but is always 0 across all 3 gateways even with 1 running at 100% loss.

All other metrics are written correctly and display correctly. I have gone over all the steps and verified them.

The potential issue with users not being written could be found here:
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/system/README.md
There is no `/var/run/utmp` and may be related be the cause.

As for the loss, no idea. Any hints to get these metrics working?

**Comment by ankou11** [comment]
I am seeing the same on the loss metrics in particular.
