### ISSUE TITLE
Uptime not Updating with multiple Firewalls

### ISSUE THREAD

**Issue by bueste** [bsmithio/OPNsense-Dashboard#33]
Hi
I've a few opnsense configured to send data with telegraf and syslog.

If I select one specific Firewall with the filter on top "OPNsense", the Uptime and Firewall will not updatet.
Same with the LAN Interface. 

Seems not all Querys have the r.host =~ /^${Host:regex}$/ and in  it.

**Comment by bueste** [comment]
In the Firewall parts, no host filter is set

**Comment by bsmithio** [comment]
Added host filters to every query that was missing them as well as added host filters for the Firewall section.
