### ISSUE TITLE
Conf file will not call temperature script correctly

### ISSUE THREAD

**Issue by ultrawyde** [BSmithIO/OPNsense-Dashboard#4]
inputs.exec section needed to be modified slightly to allow temperature script to run on my 21.7.7 install:

from:
      "/usr/local/bin/telegraf_temperature.sh"

to:
      "sh /usr/local/bin/telegraf_temperature.sh"

**Comment by kvudit** [comment]
Hello, 

I had the same issue. 
Adding sudo fixed it too

from:
"/usr/local/bin/telegraf_temperature.sh"

to:
"sudo /usr/local/bin/telegraf_temperature.sh"

**Comment by BSmithIO** [comment]
I can't reproduce this on my 21.7.7 opnsense, the temperature script runs without needing sh. I will add it to the conf file here though in case anyone else encounters this.
