### ISSUE TITLE
firewall dashboard not working properly ?

### ISSUE THREAD

**Issue by Spleenftw** [bsmithio/OPNsense-Dashboard#47]
So i put my opnsense into my FAI router DMZ so that every traffic directed at my router goes directly to my opnsense :

I am attacking from a 4G connection my FAI router and it's getting blocked as we can see below : 

![image](https://github.com/bsmithio/OPNsense-Dashboard/assets/57947900/070174c9-42c3-4375-9fa1-f890e59d1f8c)

But on my opnsense grafana dashboard, it doesnt seems to appear : 

![image](https://github.com/bsmithio/OPNsense-Dashboard/assets/57947900/409f1d39-f2e8-41f6-903b-4735432c4812)

My WAN interface is vtnet0 while my LAN interface is vtnet1.

Is there something i missed ?

**Comment by bsmithio** [comment]
Hello, I've made some updates to various parts of this dashboard that may fix this issue. 

You'll need the new compose file, dashboard JSON, and Graylog content pack.

You'll also need to enable RFC5424 in your logging targets.
![](https://camo.githubusercontent.com/806ff79995469b0fca3b12ee2b7bdafbfcdea3746287130a7ef1e40ea2522f93/68747470733a2f2f692e6e75756c732e636f6d2f58514154662e706e67)
