### ISSUE TITLE
Incorrect github url in configure.md

### ISSUE THREAD

**Issue by vadonka** [bsmithio/OPNsense-Dashboard#7]
Hello Sir!

Please update this:
curl https://github.com/bsmithio/OPNsense-Dashboard/blob/master/config/telegraf.conf

to this:
curl https://raw.githubusercontent.com/bsmithio/OPNsense-Dashboard/master/config/telegraf.conf

**Comment by bsmithio** [comment]
Done, thank you for pointing that out!

**Comment by vadonka** [comment]
You welcome, anytime! :) Really great stuff what you put together in this!
